### ISSUE TITLE
build.sh script does not work

### ISSUE THREAD

**Issue by flongo82** [MDSLab/python-iotronicclient#1]
In a Ubuntu box 16.04 when I type

`sudo ./build.sh`

it gives me the following error:

`
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/mizar/Downloads/python-iotronicclient-master/.eggs/pbr-1.9.1-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/mizar/Downloads/python-iotronicclient-master/.eggs/pbr-1.9.1-py2.7.egg/pbr/util.py", line 246, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/mizar/Downloads/python-iotronicclient-master/.eggs/pbr-1.9.1-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/mizar/Downloads/python-iotronicclient-master/.eggs/pbr-1.9.1-py2.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/mizar/Downloads/python-iotronicclient-master/.eggs/pbr-1.9.1-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/mizar/Downloads/python-iotronicclient-master/.eggs/pbr-1.9.1-py2.7.egg/pbr/packaging.py", line 710, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /home/mizar/Downloads/python-iotronicclient-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
`

but git is already installed in the system:

`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.7.4-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
`

**Comment by flongo82** [comment]
This is due to the fact that it is necessary to clone the entire git repository and only then you can call the build.sh script. 

Update the README file with an installation guide that specifies this.
